# Secrets for cookiecutter service

apiVersion: v1
kind: Secret
metadata:
  name: logstash
  namespace: default
data:
  # echo -n ${LOGSTASH_REMOTE_USER}:${LOGSTASH_REMOTE_PASSWORD} | \
  #  base64 -i - | base64 -i -
  logstash.remote.authorization: 'FIXME'
