apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    name: logstash
spec:
  type: NodePort
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
    protocol: TCP
  selector:
    name: logstash
